name: basebuild

on:
  push:
    tag:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: latest

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '>=1.20.3'

      # The prebuilt golangci-lint doesn't support go 1.18+ yet
      # https://github.com/golangci/golangci-lint/issues/2649
      # - name: Run linter
      #   uses: golangci/golangci-lint-action@v3

      # Should be built locally (./prepare_release.sh)
      - name: Build Admin dashboard UI
        run: npm --prefix=./ui ci && npm --prefix=./ui run build

      #- name: Run tests
      #  run: go test ./...

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v3
        with:
          workdir: './'
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
